# Generated by Django 3.0.8 on 2020-11-13 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_organisation_slug'),
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
