# Generated by Django 3.0.8 on 2020-11-10 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20201109_2321'),
        ('users', '0003_customuser_is_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organisation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_organisation', to='organisations.Organisation'),
        ),
    ]
