# Generated by Django 3.0.8 on 2020-11-11 12:21

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=listing.models.upload_image_to)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=listing.models.upload_image_to)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=listing.models.upload_image_to)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=listing.models.upload_image_to)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('apply_by_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=listing.models.upload_image_to)),
                ('link', models.URLField()),
                ('date_created', models.DateTimeField()),
                ('eligibility', models.TextField()),
                ('audience', models.ManyToManyField(to='listing.Audience')),
                ('level', models.ManyToManyField(to='listing.Level')),
                ('location', models.ManyToManyField(to='listing.Location')),
            ],
        ),
    ]
