# Generated by Django 3.0.8 on 2020-11-11 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listing', '0001_initial'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
