# Generated by Django 3.0.8 on 2020-10-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20201025_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
