# Generated by Django 3.0.8 on 2020-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listing_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='listing_pics'),
        ),
    ]
