# Generated by Django 3.0.8 on 2020-10-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20201025_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='eligibility',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
