# Generated by Django 3.0.8 on 2020-11-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_eligibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='audience',
        ),
        migrations.AddField(
            model_name='listing',
            name='audience',
            field=models.ManyToManyField(to='listing.Audience'),
        ),
    ]
