# Generated by Django 3.0.8 on 2020-11-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20201107_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='level',
        ),
        migrations.AddField(
            model_name='listing',
            name='level',
            field=models.ManyToManyField(to='listing.Level'),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ManyToManyField(to='listing.Location'),
        ),
        migrations.RemoveField(
            model_name='listing',
            name='typeList',
        ),
        migrations.AddField(
            model_name='listing',
            name='typeList',
            field=models.ManyToManyField(to='listing.Type'),
        ),
    ]
