# Generated by Django 3.0.8 on 2020-11-07 09:33

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20201107_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=listing.models.upload_image_to),
        ),
    ]
