# Generated by Django 3.0.8 on 2020-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_auto_20201107_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150'),
            preserve_default=False,
        ),
    ]
