# Generated by Django 3.0.8 on 2020-11-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20201109_2321'),
        ('listing', '0009_auto_20201109_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.Organisation'),
        ),
    ]
