# Generated by Django 3.0.8 on 2020-11-11 12:21

from django.db import migrations, models
import organisations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to=organisations.models.upload_image_to)),
                ('organisation', models.TextField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('website', models.URLField()),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
    ]
