# Generated by Django 3.0.8 on 2020-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.URLField(default='https://via.placeholder.com/150'),
            preserve_default=False,
        ),
    ]
