# Generated by Django 3.0.8 on 2020-11-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_auto_20201110_0017'),
        ('organisations', '0002_auto_20201109_2321'),
    ]

    operations = [
    ]
