# Generated by Django 3.0.8 on 2020-11-10 13:39

from django.db import migrations, models
import organisations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_merge_20201110_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=organisations.models.upload_image_to),
        ),
    ]
